name: eduvibe
description: "Our app serves as your dedicated study partner, guiding you to discover the most effective study strategies tailored to your learning style and goals. Whether you're delving into courses across various fields or exploring our extensive library filled with books and resources, we provide the tools necessary to enhance your studying experience. Additionally, our chatbot is on hand to offer assistance and support whenever you need it."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '3.2.0-42.2.beta'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
#  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0 # for adapting screen and font size.
  intl_phone_number_input: ^0.7.4
  pinput: ^2.2.31
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Proza Libre
      fonts:
        - asset: assets/fonts/pl_medium.ttf
        - asset: assets/fonts/pl_regular.ttf
        - asset: assets/fonts/pl_semibold.ttf
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false